//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KraceGennedy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Display(Name = "ID")]
        public int ID { get; set; }
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First name required")]
        public string firstName { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last name required")]
        public string lastName { get; set; }
        [Display(Name = "Telephone")]
        [Required(ErrorMessage = "Telephone required")]
        [RegularExpression("^[(][0-9]{3}[)] [0-9]{3}-[0-9]{4}$", ErrorMessage ="Number should be in the format (###) ###-####")]
        public string telephoneNo { get; set; }
        [Display(Name = "Role")]
        public Nullable<int> role { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email name required")]
        [EmailAddress(ErrorMessage ="Invalid email address") ]
        public string email { get; set; }
        [Display(Name = "Address 1")]
        [Required(ErrorMessage = "Address 1 required")]
        public string address1 { get; set; }
        [Display(Name = "City")]
        [Required(ErrorMessage = "City required")]
        [RegularExpression("(^Kingston$|^Montego Bay$)", ErrorMessage = "City should be Kingston or Montego Bay")]
        public string city { get; set; }
        [Display(Name = "Country")]
        [Required(ErrorMessage = "Country required")]
        public string country { get; set; }
        [Display(Name = "Latitude")]
        [RegularExpression("^[0-9]{1,9}[.][0-9]{0,6}$", ErrorMessage ="Should be a decimal ")]
        public Nullable<decimal> lat { get; set; }

        [Display(Name = "Longitude")]
        [RegularExpression("^[0-9]{1,9}[.][0-9]{0,6}$", ErrorMessage = "Should be a decimal ")]
        public Nullable<decimal> lon { get; set; }

        public virtual Role Role1 { get; set; }
    }
}
